FROM godev:latest

RUN apk update && \
    apk upgrade

RUN chmod g+w /home && \
    mkdir -p /home/project && \
    mkdir -p /user/local

EXPOSE 300
    
ENV HOME /home

# ----------------------------------------------------------------------------------------------------------------------------------------------------------

# TMUX 

## INSTALL TMUX
RUN apk add tmux

# TMUX configs
COPY .tmux.conf $HOME

# ----------------------------------------------------------------------------------------------------------------------------------------------------------

# ZSH 

## INSTALL ZSH
RUN apk add zsh

# set the zsh theme
ENV ZSH_THEME agnoster

# run the installation script  
RUN wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh || true


# ----------------------------------------------------------------------------------------------------------------------------------------------------------

# NEOVIM
## INSTALL

RUN apk add neovim

## plugin manager
RUN  curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim


RUN mkdir -p $HOME/.config/nvim/plugged
COPY init.vim $HOME/.config/nvim

# ----------------------------------------------------------------------------------------------------------------------------------------------------------

 # start zsh
  ENTRYPOINT [ "bin/zsh" ]